apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      serviceAccountName: kafka-consumer-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: kafka-consumer
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          image: tsandas/sre-playground-worker:1.0.3
          env:
            - name: KAFKA_BROKER
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: KAFKA_BROKER
            - name: KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: KAFKA_TOPIC
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: KAFKA_GROUP_ID
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: REDIS_URL
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: REDIS_PORT
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: kafka-consumer-secret
                  key: PORT
          resources:
          # requests:
          #   memory: "64Mi"
          #   cpu: "50m"
          # limits:
          #   memory: "64Mi"
          #   cpu: "50m"
          startupProbe:
            httpGet:
              path: /healthz/live
              port: 3000
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: workers
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-consumer-secret
  namespace: workers
type: Opaque
data:
  KAFKA_BROKER: a2Fma2EtY2x1c3Rlci1rYWZrYS1ib290c3RyYXAua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  KAFKA_TOPIC: dXNlci1ldmVudHM=
  KAFKA_GROUP_ID: d29ya2VyLWdyb3Vw
  REDIS_URL: cmVkaXMtc2VydmljZS5yZWRpcy5zdmMuY2x1c3Rlci5sb2NhbA==
  REDIS_PORT: NjM3OQ==
  PORT: MzAwMA==
# svc-name.namespace.svc.cluster.local
# svc-name.namespace.svc.cluster.local:port for kafka
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-consumer-network-policy
  namespace: workers
spec:
  podSelector:
    matchLabels:
      app: kafka-consumer
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kafka
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-consumer-sa
  namespace: workers
automountServiceAccountToken: false
---
